FROM python:3.12

WORKDIR /app

COPY requirements.txt .
COPY  database_init.py models.py config.py queries.py .env ./
COPY bot.py bot_web.py ./

RUN pip install --no-cache-dir -r requirements.txt

CMD python bot.py